name: Format source with clang-format
# clang_format.yml

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      # Always trigger all Github Actions if an action or something CI related was changed
      - ".github/workflows/**"
      - "tools/ci/**"
      - ".clang-format"
      # This workflow should run when a file in a source directory has been modified.
      - "src/**"

jobs:
  clang-format:
    # Github Actions checks for '[ci skip]', '[skip ci]', '[no ci]', '[skip actions]', or '[actions skip]' but not a hyphenated version.
    # It's a catch-all incase a Pull Request has been opened and someone is on auto-pilot.
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Clang Code Formatter
        uses: vstumpf/ra-clang-format-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
